# Generated by Django 4.2.11 on 2026-06-06 17:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bsd_operating_systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatingsystems',
            options={'verbose_name_plural': 'Operating Systems'},
        ),
        migrations.AddField(
            model_name='operatingsystems',
            name='End_Of_Support',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='operatingsystems',
            name='Latest_Version',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatingsystems',
            name='Package_Manger',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
