# Generated by Django 4.2.11 on 2026-06-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsd_operating_systems', '0002_alter_operatingsystems_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingsystems',
            old_name='End_Of_Support',
            new_name='End_Of_Support_For_Latest_version',
        ),
    ]
