# Generated by Django 4.2.11 on 2026-06-06 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bsd_operating_systems', '0003_rename_end_of_support_operatingsystems_end_of_support_for_latest_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystems',
            name='artitecture',
            field=models.CharField(default=django.utils.timezone.now, max_length=4000),
            preserve_default=False,
        ),
    ]
