# Generated by Django 4.2.11 on 2026-06-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsd_operating_systems', '0004_operatingsystems_artitecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingsystems',
            old_name='artitecture',
            new_name='architecture',
        ),
    ]
