# Generated by Django 4.2.11 on 2026-06-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsd_operating_systems', '0005_rename_artitecture_operatingsystems_architecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingsystems',
            old_name='Package_Manger',
            new_name='Package_Manager',
        ),
    ]
