# Generated by Django 4.2.11 on 2026-06-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsd_operating_systems', '0006_rename_package_manger_operatingsystems_package_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingsystems',
            old_name='architecture',
            new_name='CPU_Architecture',
        ),
    ]
