# Generated by Django 4.2.11 on 2026-09-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsd_operating_systems', '0007_rename_architecture_operatingsystems_cpu_architecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingsystems',
            old_name='End_Of_Support_For_Latest_version',
            new_name='End_Of_Support',
        ),
        migrations.AlterField(
            model_name='operatingsystems',
            name='CPU_Architecture',
            field=models.CharField(max_length=200),
        ),
    ]
