# Generated by Django 4.2.11 on 2026-09-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsd_operating_systems', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='operating_system',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='bsd_operating_systems.operatingsystems'),
        ),
    ]
