# Generated by Django 4.2.11 on 2026-09-07 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bsd_operating_systems', '0010_comment_updated_at_alter_comment_operating_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='operating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bsd_operating_systems.operatingsystems'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('operating_system', 'user')},
        ),
    ]
