# Generated by Django 4.2.11 on 2026-09-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsd_operating_systems', '0011_alter_comment_operating_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystems',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='operatingsystems',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
