# Generated by Django 4.2.11 on 2026-09-07 20:19

import bsd_operating_systems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsd_operating_systems', '0012_operatingsystems_logo_operatingsystems_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystems',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=bsd_operating_systems.models.logo_upload_path),
        ),
    ]
